### ISSUE TITLE
I should get reliably get a 404 when spidering an invalid page

### ISSUE THREAD

**Issue by jazeee** [veliovgroup/jazeee-meteor-spiderable#15]
In common nginx or Meteor configurations, if I visit a route that represents 404, I should see a 404 response code when spidering. (Important for SEO).

We have some discussion in #14 but should separate this in a new ticket.

Since Meteor/IronRouter seems to always return a 200 code, (which may occur after redirects etc), we may have to set some factor like Spiderable.responseCode=404, prior to completing the route.  In this scenario, we would have to do this before we indicate that the route and subscriptions are complete (using Meteor.isReadyForSpiderable = true)

**Comment by dr-dimitru** [comment]
Hi @jazeee could you please show me which changes broke 404 page handling? I would like to fix it to use on our production stage

**Comment by jazeee** [comment]
I believe that all I did was to remove these three lines:

https://github.com/jazeee/jazeee-meteor-spiderable/blob/feed4281a820e3ef54cbc520fbd083c251c56ead/lib/phantom_script.js#L60

These lines were too indiscriminate, and set status incorrectly since it was triggered on other asset files or on the websocket connection. I recall it returning 204 or 301 status randomly.

**Comment by dr-dimitru** [comment]
@jazeee I believe it fixed in latest release by `<!-- response:status-code=404 -->` ?

**Comment by jazeee** [comment]
Yes, sorry for the long delay, but this is fixed.
