### ISSUE TITLE
?_escaped_fragment_= in Google's view

### ISSUE THREAD

**Issue by Buom01** [veliovgroup/jazeee-meteor-spiderable#16]
# Hi,

I think that Spiderable should redirect crawlers from http://exemple.com/?_escaped_fragment_= to http://exemple.com/ with a 302 redirect.
Why ? Else, google detect duplicate content, not SEO friendely :(
If I say that, it's because google has also indexed my pages with `?_escaped_fragment_=`

**Comment by dr-dimitru** [comment]
@jazeee What do you think? It is not problem to implement but do we have to?
@Buom01 It is weird what Google indexes pages with `?_escaped_fragment_=`, are you sure you are using urls with hashbang `#!`?

**Comment by jazeee** [comment]
I think it would be unusual to redirect unless someone like Google
recommends this for this URL.
You should also check your Google webmaster tools and site management
settings. In that, you may have overridden the query suffix to be something
other than the default escaped fragment.

**Comment by Buom01** [comment]
Excuse me, I think to this yesterday, I would to say that my probleme was solved automaticaly
Additiaonaly, I think that google want that webmasters keep `_escaped_fragment_=` in urls:
- https://developers.google.com/webmasters/ajax-crawling/docs/specification#an-agreement-between-crawler-and-server 
- https://developers.google.com/webmasters/ajax-crawling/docs/getting-started

They explain that googlebot go on _escaped_fragment_= and automaticaly redirect users to #

And if google has indexed my home page in both version, it's because a directory of link has gived the wrong version to google. It's just that i'm impatient, google isn't stupid and now it's not in search results.

Sorry for inconvenience, now all is OK

**Comment by javdl** [comment]
And those two links are now deprecated:
http://googlewebmastercentral.blogspot.nl/2015/10/deprecating-our-ajax-crawling-scheme.html

**Comment by dr-dimitru** [comment]
@Joostvanderlaan thank you for info.
@jazeee due to this proposal - we shouldn't remove `script` tags from header. Everything else is same, as other crawlers still will use `_escaped_fragment_=`

**Comment by jazeee** [comment]
Agreed

**Comment by dr-dimitru** [comment]
Can't implement this now, as page get rendered twice, - first on server then on client. So you will have on content duplicated. Anyone know the way to let Meteor know what page is already rendered?

**Comment by javdl** [comment]
@dr-dimitru even though other crawlers still will use _escaped_fragment_= I think it's a dead end street anyhow. For example; Twitter and Facebook can use Cards & OpenGraph spec. So for those you do not need escaped fragment either.
Besides, @arunoda's Flow-Router will soon be moved into Meteor core. The coming version 4.0 of that router will support server side rendering (SSR) somewhere in January. SSR in turn will make the _escaped_fragment_= truly obsolete, cause with SSR also the crawlers which do not support JavaScript in the way Google now does will be able to crawl the pages.

**Comment by jazeee** [comment]
Agreed about Flow Router, etc.
I don't think that we can eliminate escaped fragment until we truly have
SSR. The reason is that there are other things that may depend on it, such
as text readers for blind people.
In the US, it is law that a website be accessible to blind readers.  They
would have to pass in this query to enable rendering.

Come January, it will go away, but still will need to support until people
migrate to that version.

**Comment by javdl** [comment]
@jazeee I agree :)

**Comment by jazeee** [comment]
I think this is probably closed.
