### ISSUE TITLE
Spiderable should not throw errors after running for a while (v1.2.6)

### ISSUE THREAD

**Issue by jazeee** [veliovgroup/jazeee-meteor-spiderable#18]
For some reason, this morning, after running for a week, Spiderable is failing.
I see: 

```
Exception in callback of async function: SyntaxError: Unexpected end of input
    at Object.parse (native)
    at packages/jazeee:spiderable-longer-timeout/lib/server.coffee:169:22
    at packages/jazeee:spiderable-longer-timeout/lib/server.coffee:33:2
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

**Comment by jazeee** [comment]
Restarting meteor fixes the issue.
I was able to trigger the error with curl tests, and I was getting empty content. after restarting the server and clearing Spiderable mongo cache, curl returns the correct data.

**Comment by dr-dimitru** [comment]
@jazeee  Should be fixed in #26

**Comment by jazeee** [comment]
I believe this is now fixed, and I haven't seen this issue any more.

**Comment by dr-dimitru** [comment]
This one is also: https://github.com/jazeee/jazeee-meteor-spiderable/issues/15
