### ISSUE TITLE
Empty body

### ISSUE THREAD

**Issue by dnish** [veliovgroup/jazeee-meteor-spiderable#19]
Hey guys,
I'm having some trouble with your spiderable package. I only get an empty body, but spiderable logs that everything was successfully:

```
Spiderable successfully completed for url: [200] http://www.myapp.com/about/
```

In my quellcode, I get the normal <head> section with an empty body. I'm using Ubuntu 14.04 for deployment.

If I try it on my Win 10 dev machine, I get for every single page the same content. For example, "/about" shows the content of "/" when I try to call it with "?_escaped_fragment_=".

**Comment by jazeee** [comment]
Remember the URL query has underscores:
`curl http://localhost:3000/?_escaped_fragment_=`

Can you verify that you are setting Meteor.isReadyForSpiderable = true
You must do that after your subscriptions have published.

https://github.com/jazeee/jazeee-meteor-spiderable#setup

You can test the example meteor projects as well.
https://github.com/jazeee/jazeee-meteor-spiderable/tree/master/examples

**Comment by dnish** [comment]
Sorry, my fault. You're right, the "?escaped_fragment=" was not correct.

**Comment by dr-dimitru** [comment]
Should be solved

**Comment by dr-dimitru** [comment]
@jazeee should we close this issue, and other three in this repository, all of them seems to be fixed now?
