### ISSUE TITLE
Meteor.isRouteComplete

### ISSUE THREAD

**Issue by thomasspiesser** [veliovgroup/jazeee-meteor-spiderable#2]
Hey,
could you elaborate on this sentence:

"Important You will need to set Meteor.isRouteComplete=true when your route is finished, in order to publish."

what exactly does that mean, and what would i need to do if I want to use your package?

cheers

**Comment by jazeee** [comment]
Hi, I am referring to when the code knows that your page is ready. See the code here: https://github.com/jazeee/jazeee-meteor-spiderable/blob/master/phantom_script.js
If you want to use this package, you need to set that flag to true. For example, I set it to true in my iron router base controller configuration when it has finished.
