### ISSUE TITLE
FlowRouter and template subscriptions support.

### ISSUE THREAD

**Issue by scsirdx** [veliovgroup/jazeee-meteor-spiderable#22]
Hello!

Any plans to support flowrouter and/or template-level subscriptions?

**Comment by dr-dimitru** [comment]
Flow router doesn't have anything to support in this package
in `FlowRouter.notFound` you can call render your own 404 template with `<!-- response:status-code=404 -->`
Template-level subscriptions supported as well

**Comment by scsirdx** [comment]
Hm. Ok, then there must be some mistakes in my code. I'll recheck subscriptions.

Thank you for the answer.

**Comment by dr-dimitru** [comment]
@scsirdx let me know if something not working, with code samples
