### ISSUE TITLE
Spiderable fails on 301 redirects

### ISSUE THREAD

**Issue by RobinVanCauter** [veliovgroup/jazeee-meteor-spiderable#29]
Hi,

We use nginx as a load balancer and we also configured nginx to redirect http requests to https requests using a 301 redirect. As far as I know this is a pretty standard practice.

The problem is, when these redirects are set up, spiderable breaks.

When I try to debug using cURL I get the following messages on the server;

`Spiderable successfully completed for url: [301] http://example.com/`

No matter wether I request the https variant or the http variant (using -L option to follow redirects) this is the message the server returns.

When I cURL the http variant I get the default HTML template with an empty body.
When I cURL the https variant I get a cut off reply liek this;
`<!DOCTYPE html><html class="mdl-js"><head>
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/a2913909d55c402a37441da83f5dcecd33a2a431.css?meteor_css_resource`

We would still like to redirect our users to the https variant of our website since it is required for checkout using PayPal + overall privacy concerns. But we would also like to serve google a crawlable page.

Any idea on what we might be doing wrong here? Or is there anything else we might try to debug this a bit further?

Thanks in advance!

**Comment by dr-dimitru** [comment]
> When I cURL the https variant I get a cut off reply like this...

Sound like a problem on your end, because when you just cURL direct link without `-A Google` or `?_escaped_fragment_=` it should return unrendered and plain HTML-code.

**Comment by RobinVanCauter** [comment]
But when I cURL direct link it DOES return unrendered and plain HTML-code..

Only when I use escaped fragment or the google useragent it breaks and only when HTTPS redirects are turned on, when I turn these off in nginx, spiderable works perfectly.

**Comment by dr-dimitru** [comment]
How do you redirect users? I'm asking this because user should be redirected before hitting Meteor app.

**Comment by RobinVanCauter** [comment]
I've got nginx running on the same server as my Meteor app, nginx listens on the 80 and 443 ports and proxies requests to the Meteor app. In the server config of ningx for my app I also check if a user is trying to connect using http and if it does I redirect it to the https variant using a 301 redirect. 

Something like this (the $conn_type variable is set to this value if it detects a connection using port 80);

```
if ($conn_type = non-ssl-no-ie) {
    return 301 https://$server_name$request_uri;
}
```

EDIT: I am using Ajenti for settings this up so I'll have a look if it's maybe generating a funky config file but in the browser everything is working fine with this configuration.

**Comment by dr-dimitru** [comment]
Are you sure it is working properly? Now it doesn't look like this... By my experience (_and a logic_) you should not hit Meteor, unless redirected. On nginx we using different redirecting logic, than yours. Via separate server which listens this exact domain on 80 port, and redirect all requests to https version. 

Try to remove this package temporarily and cURL your server again. 
To make sure add an extra headers to identify which server instance is replying to you.

**Comment by RobinVanCauter** [comment]
Alright, thanks.

From what I can see Ajenti puts both 443 and 80 listen directives under one server block. I'll try with a manual nginx config file more like your setup and see if that fixes it.

Thanks for the quick respones btw!

**Comment by dr-dimitru** [comment]
@T-Grave welcome! Let me know then.

**Comment by RobinVanCauter** [comment]
So I created a manual configured configuration file for nginx, and everything is still the same as before.
Note that I also cleared the spiderable cache before testing again.

When I try and fetch the https page (which doesn't redirect at all) I get;

```
<!DOCTYPE html><html class="mdl-js"><head>
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/a2913909d55c402a37441da83f5dcecd33a2a431.css?meteor_css_resource
```

And on the server it shows:
`Spiderable successfully completed for url: [301] http://example.be/`
This is what my configuration looks like;

```
server {
        listen          80;
        server_name     example.be www.example.be;
        return          301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;

    ssl_certificate /path/fullchain.pem;
    ssl_certificate_key /path/privkey.pem;
    server_name example.be www.example.be;

    access_log /var/log/nginx/vg-platform-ssl.access.log;
    error_log /var/log/nginx/vg-platform-ssl.error.log;

    location  / {

        # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass http://localhost:6014;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header HTTPS   $https;

    }
}
```

**Comment by dr-dimitru** [comment]
post your Spiderable settings, maybe you're setting `Meteor.isReadyForSpiderable = true` too early?

**Comment by RobinVanCauter** [comment]
I don't have any Spiderable settings set except for `Spiderable.debug = true;`

This is the homepage code;

```
   Template.home.onCreated(function(){
      const instance = this;

      instance.subscribe('buildTemplates');
      instance.subscribe('buildClassifications');
   });

   Template.home.onRendered(function() {
      const instance = this;

      instance.autorun(function() {
         if(instance.subscriptionsReady()) {
            Meteor.isReadyForSpiderable = true;
         }
      });
   });
```

**Comment by RobinVanCauter** [comment]
Are you using spiderable behind a nginx configuration yourself? Because I've been searching on google to find anything on the matter and there's multiple stackoverflows of people having trouble with nginx and spiderable :/

**Comment by dr-dimitru** [comment]
yes, on 4 projects already.
As we use distributed servers (cluster) our config is a bit complex, and we use Passenger Phusion, but cluster nodes have next config (should work directly):

```
server{
  listen 443;
  listen [::]:443;
  server_name example.com wss.example.com;

  root /var/www/example.com/public;

  passenger_enabled on;
  passenger_app_type node;
  passenger_startup_file main.js;
  passenger_sticky_sessions on;
  passenger_friendly_error_pages off;

  passenger_env_var MONGO_URL mongodb://localhost:27017/example;
  passenger_env_var MONGO_OPLOG_URL mongodb://usr:pass@localhost:27017,localhost:27018,localhost:27019/local?authSource=admin;
  passenger_env_var ROOT_URL https://example.com;
  passenger_env_var METEOR_SETTINGS '{"public":{}}';
  passenger_env_var DDP_DEFAULT_CONNECTION_URL https://wss.example.com;

  ssl on;
  ssl_certificate /etc/nginx/ssl/example.com.crt;
  ssl_certificate_key /etc/nginx/ssl/example.com.key;
  ssl_session_cache shared:SSL:1m;
  ssl_session_timeout 5m;

  location / {
    if ($request_uri ~* /sockjs/) {
      access_log              off;
    }
  }

  location ~ \.(aspx|php|jsp|cgi|asp)$ {
    return 410;
  }
}


server {
  listen 443;
  listen [::]:443;
  server_name "~^(?!.*wss)(.*)\.example\.com$";
  return 301 https://example.com$request_uri;
}

server {
  listen 80;
  listen [::]:80;
  server_name *.example.com example.com;
  return 301 https://example.com$request_uri;
}
```

But I definitely recommend next servers scheme (secure and reliable):
[some load-balancer or just proxy] -> [[phusion] -> [nginx instance] -> [node.js instance]]

And I don't settings anywhere `Meteor.isReadyForSpiderable` at all.

**Comment by RobinVanCauter** [comment]
Ok, I'll spin up a new VPS and try using it in combo with Phusion, sure looks very interesting!

Also, I'm running Ajenti-V and I've been digging a bit and it sure doesn't look like it's using a "regular" version of nginx, so I'm guessing it's just Ajenti misconfiguring nginx.

I'll keep you posted

**Comment by dr-dimitru** [comment]
Never facing Ajenti-V, so can't tell you anything.
Hope I'm pointed you to right direction.
Let me know if you have any issues with phusion (setup is a bit tricky, and takes time, thanks they have expressive, but not obvious docs).

**Comment by jazeee** [comment]
Just to add clarity, can you post your full curl command.
If you run: `curl https://www.example.be`, then you should get meteor's response which is uncompiled, and contains an empty body. This should be the same as if you browsed in Chrome and looked at the page source. (Specifically, Ctrl+u, or Right Click "View Page Source")

In order for Spiderable to compile the page, you should use something like:

``` bash
curl  -A Google https://www.example.be
curl https://www.example.be?_escaped_fragment_=
```

We use Spiderable on our site and we proxy SSL using nginx in a similar manner to the descriptions above. It works as expected.
Please let us know what command you used for debugging.
Thanks.

_EDIT_
If you use -A Google or add the _escaped_fragment_= query in curl, or even in a browser, you are triggering Spiderable to render the page using phantomJS. Spiderable waits for Meteor code to set `Meteor.isReadyForSpiderable=true`, before returning.  See https://github.com/jazeee/jazeee-meteor-spiderable/blob/master/lib/phantom_script.js#L21

If Spiderable is pausing, one reason is that your Meteor code is not setting this flag.
To simplify the test, you can move the flag to be run instantly. If Spiderable completes instantly, then you can see that it is working, even though it will be too soon. You can then figure out why it is not being set in your subscription.

Alternatively, you can try some of the example Meteor apps to see how it works.

**Comment by jazeee** [comment]
One other test: In Chrome, under normal browsing conditions, open the Chrome debugger console (Ctrl + Shift + I) and verify that `Meteor.isReadyForSpiderable === true`
If it is false in Chrome, then you are not setting it correctly.
Generally, you want to set the flag once the client has received all subscriptions.
Remember also, that if you subscribe, that all publications must either return a reactive object or a Mongo cursor, or `return this.ready()`  
Some discussion on `this.ready()`, see: https://themeteorchef.com/snippets/publication-and-subscription-patterns/#tmc-simple-publications

Sometimes, we publish with conditionals. On fail conditions, we must still return a reactive variable. `return this.ready()` completes the publication for those cases.

Note - I believe you have to return it, and not just call it, but I am not 100% sure.

**Comment by dr-dimitru** [comment]
Weird. I decide to check how is it working on our servers (all have pretty same configs). And one of them failing with: 

```
Segmentation fault.
/bin/sh -c phantomjs  --load-images=no --ssl-protocol=TLSv1 --ignore-ssl-errors=true --web-security=false /var/www/example.com/programs/server/assets/packages/jazeee_spiderable-longer-timeout/lib/phantom_script.js "https://example.com"
```

Have any of you facing this problem? It was working like 2 days ago. No changes, no updates, even no one was logging in this server. I've upgraded linux packages, including phantom and nodejs - but this not solved the issue.

**Comment by jazeee** [comment]
I haven't seen that issue. Occasionally, I do see runaway phantomjs
processes, and kill old ones.
You should be able to run the phantimjs command on the console and see why
it is failing.
On my dev system, I also updated node, and I ended up having to flush some
compiler cache, probably containing native code compilation that was no
longer compatible. That may cause segfaults.

**Comment by dr-dimitru** [comment]
Locally running the same command - woking like a charm. Weird.

**Comment by RobinVanCauter** [comment]
@jazeee I ran the exact same curl commands as you did for debugging

I also set the variable correct as can be seen here in the browser:
![image](https://cloud.githubusercontent.com/assets/7956579/12373032/214a5f2a-bc6c-11e5-9ea7-a4eb22a707fe.png)

And I do set it at the right time (as can be seen in one of my posts above, I set it after all template subscriptions have been completed)

Would you mind sharing your nginx configuration files for reference?

**Comment by dr-dimitru** [comment]
And a dump file it generates on crash (aka crash-report) has nothing to investigate with. No memory leaks, or overuse is found.

**Comment by RobinVanCauter** [comment]
Alright, so, I finally tracked down the problem. The clue lies in my initial post in this issue;

![image](https://cloud.githubusercontent.com/assets/7956579/12373268/149f9f30-bc74-11e5-825e-8f79fef1d561.png)

I wasn't aware of the fact that Spiderable uses the ROOT_URL environment variable for getting the page contents. After I read about this 10 minutes ago I checked my ROOT_URL and there it was, the cause of my problem.

It was set to: `http://example.com`, this broke Spiderable as my nginx config redirects http requests using a 301, Spiderable always returned a 301 code and thus broke off creating a rendered HTML output (as a 301 indicates that the content it's looking for is no longer there but moved).

**Solution:**
I changed it to `https://example.com` and now all is working fine and as expected even with my original setup :)

Closing the issue since my problem is solved!

**Comment by verishal** [comment]
when i hit url:
http://example.com/?_escaped_fragment_=
but
only In https request time not working .
https://example.com/?_escaped_fragment_=

that time page is not render. how can resolve this issue.
please help

my .htacesss file
```htacesss
RewriteEngine On
RewriteCond %{HTTPS} !=on

RewriteRule ^(.)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
# Tried for SSR -Verishal
Options +FollowSymLinks
RewriteCond %{REQUEST_URI} ^/$
RewriteCond %{QUERY_STRING} ^escaped_fragment=/?(.)$
#RewriteCond %{QUERY_STRING} escaped_fragment=/([^&])
RewriteRule ^/(.) http://example.com:9090/$1 [R,L]
ProxyPassReverse / http://example.com:9090/
Options Indexes FollowSymLinks MultiViews
```
Production envirment url:
phantomjs --disk-cache=no --ssl-protocol=TLSv1 --ignore-ssl-errors=true --web-security=false /opt/bitnami/apache-tomcat/staging/ROOT/js/angular-seo-server.js 9090 https://example..com/

**Comment by dr-dimitru** [comment]
@verishal 
 1. Are you at the right repo?
 2. Have you installed this package? If, so it will spawn `phantomjs` process for you, and handle requests from Crawlers, so you have no need to run `phantomjs` separately and have special rules at `.htacesss` configuration

**Comment by verishal** [comment]
*dr-dimitru* thank you response,
But without phantomjs  how can handle requests from Crawlers,
i refered this link.https://github.com/BeOleg/angular-seo.

**Comment by dr-dimitru** [comment]
@verishal wrong repo.
This package is specific for Meteor.js

**Comment by verishal** [comment]
thank you.  dr-dimitru. Can you send me link for referred. i can implement.
i'm so stuck this issue.

**Comment by dr-dimitru** [comment]
Sounds like you need to ask at the Apache forum for config fix.

 1. Take a look on [prerendering](https://ostr.io/info/prerendering)
 2. [This link should help too](https://www.google.ru/search?q=phantomjs+htaccess+example&oq=phantomjs+htaccess+example)

**Comment by verishal** [comment]
dr-dimitru .thank you.

**Comment by verishal** [comment]
hello dr-dimitru i'm work in angular js. how  can implement ? 
prerendring.please give idea.
