### ISSUE TITLE
Rendering works on undefined routes, but not on defined

### ISSUE THREAD

**Issue by dnish** [veliovgroup/jazeee-meteor-spiderable#30]
Hey,
I'm having a strange problem with Spiderable. If I call f.e. <code>mysite.com/?_escaped_fragment_=</code> I get the following error on my server and get redirected to the normal site on client side:

```
spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' }
```

If I now call <code>mysite.com/blablabla/?_escaped_fragment_=</code> I get the rendered version of my start page. Any ideas how Spiderable doesn't work on defined works, but works on undefined routes?

**Comment by jazeee** [comment]
Not sure. It works for us in Meteor 1.2.1
Have you configured the 404 templates as necessary, and also set Meteor.isReadyForSpiderable=true after your subscriptions are ready.
See:
https://github.com/jazeee/jazeee-meteor-spiderable#important

**Comment by dnish** [comment]
It was a problem with RTCMultiConnection, I've added it to client/classes - after declaring it as own package, everything worked fine again.
