### ISSUE TITLE
Spiderable.ignoredRoutes is only available in server code

### ISSUE THREAD

**Issue by imajus** [veliovgroup/jazeee-meteor-spiderable#35]
You should either state in the readme that `Spiderable.ignoredRoutes.push(…)` must be in server-only code or provide a dummy value for client code.
Currently I get `Uncaught TypeError: Cannot read property 'push' of undefined` on client in development mode which doesn't affect overall site behaviour but completely breaks the site down when deployed on production server.

**Comment by dr-dimitru** [comment]
This package is server only

**Comment by imajus** [comment]
That's not true, I had to set `Meteor.isReadyForSpiderable = true;` in client code.

**Comment by dr-dimitru** [comment]
Yes, you're right, minor part like `isReadyForSpiderable` and `fragment` meta-tag is set on Clientю

**Comment by jazeee** [comment]
Thanks for the clarification. I added a note to the readme.
