### ISSUE TITLE
Multitenant and subdomains : Use request header hostname instead of Meteor.absoluteUrl()

### ISSUE THREAD

**Issue by Alexander-Urbina** [veliovgroup/jazeee-meteor-spiderable#36]
Hi,
Nice package, it was the only one working for me, I've tried with an app that has subdomains and it returns the same page with `?_escaped_fragment_=` in all of the subdomains. I'm not sure, but it seems related to use `Meteor.absoluteUrl()` insted of  `req.headers.host`. I've reviewed the collection for SpiderableCacheCollection and it takes only the Meteor.absoluteUrl()
Would you consider make changes [like this](https://github.com/WyvrnCo/spiderable/commit/96b890b14dded92b6773e325abd2a7ab1eb50e93#diff-287eee98cb072b73178dff67d5ca5755L62) ?

**Comment by jazeee** [comment]
Assuming it works, I think this would be a reasonable change.
We'd change it here:
https://github.com/jazeee/jazeee-meteor-spiderable/blob/master/lib/server.coffee#L110

**Comment by jazeee** [comment]
Note that the last comment on this link indicates that it isn't a great solution.:
http://stackoverflow.com/questions/10348906/how-to-know-if-a-request-is-http-or-https-in-node-js

Quoted:

> Note that this will only work if your app is running behind a reverse proxy that sets this header

**Comment by jazeee** [comment]
I am unsure what is the right solution here, so will need to investigate further. Node `url` module probably will help.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
