### ISSUE TITLE
PhantomJS  failed

### ISSUE THREAD

**Issue by catin-black** [veliovgroup/jazeee-meteor-spiderable#37]
Hi. I have a problem

```
spiderable: phantomjs failed: { [Error: Command failed: /bin/sh -c phantomjs  --load-images=no --ssl-protocol=TLSv1 --ignore-ssl-errors=true --web-security=false /bundle/bundle/programs/server/assets/packages/jazeee_spiderable-longer-timeout/lib/phantom_script.js "https://taptospeak.com/route/path#!:"
]
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '/bin/sh -c phantomjs  --load-images=no --ssl-protocol=TLSv1 --ignore-ssl-errors=true --web-security=false /bundle/bundle/programs/server/assets/packages/jazeee_spiderable-longer-timeout/lib/phantom_script.js "https://mywebsite.com/route/path#!:"' }
```

I have no idea how to find solution.

**Comment by dr-dimitru** [comment]
@catin-black Have you installed phantomjs?

**Comment by jazeee** [comment]
It very much looks like you need to install PhantomJS.
You can test manually by running the cmd parameter on the shell.

Also, look at the readme for setup and usage instructions.

/bin/sh -c phantomjs  --load-images=no --ssl-protocol=TLSv1
--ignore-ssl-errors=true --web-security=false
/bundle/bundle/programs/server/assets/packages/jazeee_spiderable-longer-timeout/lib/phantom_script.js
"https://mywebsite.com/route/path#!:"

**Comment by catin-black** [comment]
Yeap, I have phantomjs.
I tried to reinstall it but it did not help

**Comment by jazeee** [comment]
Did you try to run the same command that is in the error?
`/bin/sh -c phantomjs  --load-images=no --ssl-protocol=TLSv1 --ignore-ssl-errors=true --web-security=false /bundle/bundle/programs/server/assets/packages/jazeee_spiderable-longer-timeout/lib/phantom_script.js "https://mywebsite.com/route/path#!:"`

What does it generate?

Out of curiosity, are you on a Mac? I've only tested on Linux.

**Comment by catin-black** [comment]
> What does it generate?

Nothing, but on docker image and on server I have installed phantom

**Comment by jazeee** [comment]
Does it hang forever, or does it terminate with no output?
If it is hanging, then you are probably not setting the flag for
isReadyForSpiderable . See readme.

**Comment by catin-black** [comment]
> Does it hang forever, or does it terminate with no output?

terminate with no output
I am using Meteor.isReadyForSpiderable when this.ready().
It does not work even when I have no publications.

**Comment by jazeee** [comment]
I recommend that you look at testing `phantomjs` using modified versions of `/bundle/bundle/programs/server/assets/packages/jazeee_spiderable-longer-timeout/lib/phantom_script.js`
Start with a really stripped down version of that script, and verify that you get some output. then add more features until it fails.
Without more information, there is no real way to diagnose your issue.

**Comment by xauxatz** [comment]
I have the same problem. catin-black, did you ever find a solution?

**Comment by dr-dimitru** [comment]
Please update to latest release.
Feel free to reopen it in case if the issue still persists on your end.
