### ISSUE TITLE
Meteor 1.4 + React: 204 No content

### ISSUE THREAD

**Issue by dnish** [veliovgroup/jazeee-meteor-spiderable#39]
Hey,
I'm having a issue with your package on my local dev machine. I'm using Meteor 1.4 with React and getting <code>204 No content</code> after requesting http://localhost:3000/?_escaped_fragment_= Spiderable debug doesn't show anything. Does this package still work with 1.4?

**Comment by dr-dimitru** [comment]
@dnish 
It's should be `http://localhost:3000/?_escaped_fragment_=` (two underscores is missed)

**Comment by dnish** [comment]
@dr-dimitru Yeah, I've used the second one. GitHub removes it when it is wrapped into code. After calling it nothing happens on the page, instead I can see the 204 response in my network console.

**Comment by dr-dimitru** [comment]
@dnish drop the cache and try again

**Comment by dnish** [comment]
I've just tried, even in privacy mode I get a 204 if I add the escaped fragment parameter. All other query parameters work fine.

**Comment by dr-dimitru** [comment]
I've meant cache of this lib, the mongo collection

**Comment by dnish** [comment]
The SpiderableCacheCollection is empty

**Comment by dr-dimitru** [comment]
Use `Spiderable.debug = true` to see what is going on

**Comment by dnish** [comment]
I'm getting this message in my console:

```
Meteor application returned empty response
```

**Comment by dr-dimitru** [comment]
@dnish Phantomjs binary is installed on your machine?

**Comment by dnish** [comment]
Yep, I'll try now to install it again. Maybe it doesn't work right because of the MacOS upgrade.

**Comment by dr-dimitru** [comment]
Better to compile it locally

**Comment by dnish** [comment]
Mh okay, reinstalling solved the issue. But now I get only an empty page without the rendered React components in it. Pages is saved within SpiderableCacheCollection.

**Comment by dr-dimitru** [comment]
Hello @dnish ,

I know it's kind of late. But we just updated library to work with latest Meteor and we have all new codebase. Could you test it on your end?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
