### ISSUE TITLE
Spiderable + 301 Redirect

### ISSUE THREAD

**Issue by naho2081** [veliovgroup/jazeee-meteor-spiderable#40]
Hey @jazeee .

It seems that 301 works incorrectly because it doesn't pass back to client `'Location'` value in the headers of the 301 redirect. 

Or am I missing something?

To fix this something like this must be added to `server.coffee`:

```
location = output.content.match /.*(location url="(.*)").*/mi
  if location?[2]
    output.headers.push
      name: 'Location'
      value: location[2] 
```

In this example `location url = <REDIRECT URL>` is added to HTML contents by 301 Redirect Template.

**Comment by dr-dimitru** [comment]
Hello @naho2081 ,

This package returns only `200` response code, or custom [response status](https://github.com/jazeee/jazeee-meteor-spiderable#response-statuses) made via markup.

For your case best option is [ignore such paths](https://github.com/jazeee/jazeee-meteor-spiderable#ignoredroutes-string).

Let me know if it helps

**Comment by naho2081** [comment]
Hey @dr-dimitru,

yep, we are adding 301 response code using template with following contents

```
div(class='hidden')
	<!-- response:status-code=301 -->
```

But as I have written above, we must also adjust package and add redirect url into the header.
Otherwise redirect will not work properly.
