### ISSUE TITLE
Transfer ownership of repository

### ISSUE THREAD

**Issue by jazeee** [veliovgroup/jazeee-meteor-spiderable#45]
We should transfer ownership of this repository to @dr-dimitru 

See https://help.github.com/articles/about-repository-transfers/

The requirements:
1. @dr-dimitru fork will need to be renamed, otherwise I cannot transfer

The considerations:
1. It should not affect Atmosphere, since Github will do a redirect automatically (301?)
1. It should not affect forks within github.
1. Github recommends updating local clones using `git remote`

There may be some other considerations, but I believe the risk is quite low.

**Comment by dr-dimitru** [comment]
@jazeee what if you create a Team on GitHub with access only to this repository and make me an admin for this Team?

**Comment by jazeee** [comment]
May work. I think I need to create an organization first. I'll do that.

**Comment by jazeee** [comment]
Name? meteor-spiderable-cached sound good?

**Comment by jazeee** [comment]
Actually, I don't think an organization would solve it, since the URL would include the organization name.

**Comment by dr-dimitru** [comment]
You're right, transferring repository to me is the easiest option

**Comment by dr-dimitru** [comment]
@jazeee I believe if we'll change [this line](https://github.com/jazeee/jazeee-meteor-spiderable/blob/master/package.js#L5) to my fork on next release. It will be fine.

**Comment by jazeee** [comment]
Probably. I believe that line can be changed after the next meteor publish.
It doesn't have to change immediately, since the github redirect will be pretty transparent.

Note - I wonder if an organization is a better option, since you may eventually want to add other contributors, or transfer ownership yourself at some point. If so, create an organization, and I'll transfer ownership to that. Otherwise I'll transfer to you.
Either way works...

**Comment by dr-dimitru** [comment]
Sure, I'm keeping most of the projects under [@VeliovGroup](https://github.com/VeliovGroup) organization. Feel free to transfer repository to [@VeliovGroup](https://github.com/VeliovGroup) organization

**Comment by jazeee** [comment]
Ok, I can do that. The only issue is that the repos (a fork) already exists. You'd have to rename that first, then I can transfer it.

**Comment by jazeee** [comment]
The error message:
`VeliovGroup/jazeee-meteor-spiderable already exists and You don’t have the permission to create repositories on VeliovGroup`

Actually, that suggests I won't be able to transfer to it anyway, since I don't have permission.

**Comment by dr-dimitru** [comment]
I've removed the fork.

Do you have "Transfer" in repository settings (settings > options > danger zone > Transfer)?

![screen shot 2017-03-02 at 2 30 24 am](https://cloud.githubusercontent.com/assets/1686778/23486292/5808d3bc-fef0-11e6-90e8-7fbefa5f961d.png)

**Comment by jazeee** [comment]
Yes I do have that option. It now only has this error: `You don’t have the permission to create repositories on VeliovGroup`

Edits:
I could transfer to you and you can then move to the org except for this error: `dr-dimitru/jazeee-meteor-spiderable already exists`

**Comment by dr-dimitru** [comment]
Try now, renamed

**Comment by jazeee** [comment]
Argh. Now says: `dr-dimitru already has a repository in the jazeee/jazeee-meteor-spiderable network`

**Comment by jazeee** [comment]
From the docs: When you transfer a repository to a new owner, they can immediately administer ... must not have a repository with the same name, or a fork in the same network.

**Comment by dr-dimitru** [comment]
well, okay, removed now

**Comment by jazeee** [comment]
I believe you'll just need to accept the transfer... (technically, not closed, but close)

**Comment by dr-dimitru** [comment]
Done, successfully. Github redirect is fine
