### ISSUE TITLE
Crashing on angular-meteor

### ISSUE THREAD

**Issue by alkaj** [veliovgroup/jazeee-meteor-spiderable#47]
I found this package very interesting as i can decide when to release the content for spiders, but it crashes right after the  installation ends with an "unexpected token (1, 81)", could someone help? i did not found any reference to this error anywhere so i conclude that it is specific to my installation; i am using Meteor 1.4.2.3 along with Angular.
thanks in advance

**Comment by dr-dimitru** [comment]
Hello @alkaj ,

Could you post more info about error? Full error stack, is it happens on Client or Server? How do you request "rendered" version?

**Comment by alkaj** [comment]
Hello @dr-dimitru, the error is thrown immediately after the installation ends as the server is not able to process startup anymore, here is the complete error stack:
```
=> Errors prevented startup:

   While building for web.browser:
   lib/spiderable.js:1:81: Unexpected token, expected , (1:81)

   While computing assigned variables:
   /packages/jazeee_spiderable-longer-timeout/lib/spiderable.js: Unexpected
   token, expected , (1:81)

   While building for os.linux.x86_64:
   lib/spiderable.js:1:81: Unexpected token, expected , (1:81)

   While computing assigned variables:
   /packages/jazeee_spiderable-longer-timeout/lib/spiderable.js: Unexpected
   token, expected , (1:81)

=> Your application has errors. Waiting for file change.
```
thanks...

**Comment by dr-dimitru** [comment]
Is `ecmascript` package installed to your app?

**Comment by alkaj** [comment]
No it is not, it got removed when installing the `angular` package, 
it can not be added because of conflict with the `pbastowski:angular-babel` package on `*.js` files.

**Comment by dr-dimitru** [comment]
@alkaj why not switch to NPM `babel-runtime`?

**Comment by dr-dimitru** [comment]
From `pbastowski:angular-babel` docs 

> The discussion here is for Meteor 1.2 only.

So, quick guess - you don't need it on `Meteor@1.4.2.3`

**Comment by alkaj** [comment]
seems like the problem discussed persist anyhow...

**Comment by SimonatoLucaManuele** [comment]
I've the same problem.. i'm not using angular.

SOLVED -> my ecmascript module wasn't updated at his last version

**Comment by dr-dimitru** [comment]
@SimonatoLucaManuele thank you for report

@alkaj is it solved on your end?

**Comment by alkaj** [comment]
@dr-dimitru I finally opt-out for the greenydragonny:spiderable-ui-router that actually works well with the angular ui-router.

**Comment by dr-dimitru** [comment]
@alkaj I assume we can close this one

Feel free to reopen it in case if the issue still persists on your end.
