### ISSUE TITLE
Spiderable.ignoredRoutes not working

### ISSUE THREAD

**Issue by mizsha** [veliovgroup/jazeee-meteor-spiderable#52]
hi, iam using Spiderable.ignoredRoutes configuration directive, but spiderable still trying to fetch page.

while i debug library i think problem is in 

```
  return next();
});
```

at end of server.js

Thanks for help,
M

**Comment by dr-dimitru** [comment]
Hello @mizsha ,

> return next();

Means proceed to the next registered request handler if Spiderable criteria is not met.

Could you please post how you add `Spiderable.ignoredRoutes`, or better full code related to `Spiderable` package.

**Comment by mizsha** [comment]
.... now i think return next(); is not problem, its working, but i got this error:

`spiderable: phantomjs failed at http://localhost:3003/storage/9n4ps6JZHXo8wzXGb/thumbnail.jpg: { [Error: Command failed: /usr/bin/env bash -c exec phantomjs  --load-images=no --ssl-protocol=TLSv1 /dev/stdin <<'END'
I20170816-17:16:41.922(2)? var url = "http://localhost:3003/storage/9n4ps6JZHXo8wzXGb/thumbnail.jpg";// 'url' is assigned to in a statement before this.
I20170816-17:16:41.922(2)? var page = require('webpage').create();
I20170816-17:16:41.924(2)? 
`

It probably means another handler after next () is an original spiderable package.

its possible to disable original package or best practice to import jazeee-meteor-spiderable package ?

Meteor 1.4.3.2

thanks

**Comment by mizsha** [comment]
i have i

i am using https://atmospherejs.com/joshowens/shareit and it depends on spiderable package, after removing dependency, everything is ok and working

Thanks for your help,
M

**Comment by dr-dimitru** [comment]
@mizsha yes, original spiderable package must be removed. I'm glad it's solved.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/jazeee-meteor-spiderable)
 - Star on [Atmosphere](https://atmospherejs.com/jazeee/spiderable-longer-timeout)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
