### ISSUE TITLE
Showing Iron:Router's message on my homepage

### ISSUE THREAD

**Issue by kenshinman** [veliovgroup/jazeee-meteor-spiderable#53]
Hi, thanks for this package.
I just tried it and it's showing me 
Iron:Router's message on my homepage.

in the debug console, o get this
`Spiderable successfully completed [from cache] for url: [200] http://localhost:3000/`
meaning it was successful.
How can I solve this?

Thanks

**Comment by dr-dimitru** [comment]
Hello @kenshinman ,

 1. Start with purging Spiderable cache (*removing all records from `SpiderableCacheCollection` collection*)
 2. Does your app works directly? (*without involving Spiderable*)
 3. What version of Meteor and `jazeee-meteor-spiderable` you are on?

**Comment by kenshinman** [comment]
Hey! Really excited I got a response. Thanks
1. Done
2. Yes. When I run `curl http;//localhost:3000/` all looks fine but when i run `curl http://localhost:3000/?_escaped_fragment_=`, i get the iron-router default page.

I'm on Meteor@1.3.5.1 and jazeee:spiderable-longer-timeout@1.2.13

here is how I wrote the route
``` 
   Router.route("/", {
  name: "home",
  waitOn: function() {
    return [
      Meteor.subscribe("sub1"),
      Meteor.subscribe("sub2"),
    ];
  },
  layoutTemplate: "homeLayout",
  template: "home",
  onAfterAction: function() {
    if (this.ready()) {
      Meteor.isReadyForSpiderable = true;
    }
  }
});
````

**Comment by kenshinman** [comment]
Hi @dr-dimitru ,
Just created a fresh project now and added the package and it works perfectly
I guess the cause of the clash is iron router. my current version is `1.0.13`
Issue still persists on my app though. Thanks

Here's the link to the project [Link](http://sesewa.org?_escaped_fragment_=)

**Comment by kenshinman** [comment]
# **Ureka**
Found the solution 
all I did was this `curl http://localhost:3000?_escaped_fragment_=`  and not `curl http://localhost:3000/?_escaped_fragment_=`

The difference is the `/` between the `0` and the `?` and that's all. Wonder why this is an Issue though...

Not sure how crawlers visit the web app whether it's the (working one for me) or the second.

Thanks a lot.

**Comment by kenshinman** [comment]
I think the issue is with iron router as prerender.io now gives the same issue. My routes are quite much but may need to migrate to flow router

**Comment by dr-dimitru** [comment]
[You're welcome](https://github.com/VeliovGroup/flow-router).
I bet you have ES6/7 syntax used in NPM (*NPM packages written in ES6/7 won't be transpiled to ES5*) and prerender.io nor spiderable package has no ES6/7 syntax support.
Try [prerendering service](https://ostr.io/info/prerendering) with ES6/7 support, at least to test your code (*free tier with up to 240 free renders*).

**Comment by kenshinman** [comment]
thanks @dr-dimitru for the help so far. I really appreciate

I have tried this one too the prerendering service too and I have the same iron router splash screen

**Comment by dr-dimitru** [comment]
@kenshinman weird. 

 1. Do you have any errors on server or client?
 2. Issue appears on all pages or only `/` *root*?

**Comment by kenshinman** [comment]
Hi @dr-dimitru . It (the [prerender service](https://ostr.io/info/prerendering)) works now. All I had to do was Enable ES6.
Thanks so much for all the help

**Comment by dr-dimitru** [comment]
@kenshinman great, I'm glad it helped
